using ERP.Areas.Owners.Data;
using ERP.Areas.Owners.Models;
using ERP.Areas.Owners.Models.Identity;
using ERP.UnitOfWork;
using ERP.Utilities;
using ERP.Utilities.Services;
using ERP.Utilities.Services.EmailService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace ERP.Areas.Owners.Controllers
{
    [Area("Owners")]
    [Route("api/[Area]/[controller]")]
    [ApiController]
    public class GeneralsController : ControllerBase
    {
        public OwnerUserManager OwnerManager { get; set; }
        public OwnerRoleManager RoleManager { get; set; }
        public ITokenService TokenService { get; }
        public IUnitOfWork_Owners OwnersUnitOfWork { get; }
        public DbContextOptions<OwnersDbContext> DbOptions { get; }
        public OwnerSignInManager OwnerSigninManager { get; }
        public IMailService MailService { get; }
        public Constants Constants { get; set; }

        public GeneralsController(OwnerUserManager ownerManager, ITokenService tokenService, Constants constants,
            IUnitOfWork_Owners ownersUnitOfWork, DbContextOptions<OwnersDbContext> dbOptions,
            OwnerSignInManager ownerSigninManager, IMailService mailService, OwnerRoleManager roleManager)
        {
            OwnerManager = ownerManager;
            TokenService = tokenService;
            Constants = constants;
            OwnersUnitOfWork = ownersUnitOfWork;
            DbOptions = dbOptions;
            OwnerSigninManager = ownerSigninManager;
            MailService = mailService;
            RoleManager = roleManager;
        }

        [HttpGet(nameof(GetCountries))]
        [AllowAnonymous]
        public async Task<ActionResult<List<Country>>> GetCountries()
        {
            var countries  = await OwnersUnitOfWork.Countries.GetAllAsync();
            if(countries.Count == 0)
            {
                await FillInCountries();
                countries = await OwnersUnitOfWork.Countries.GetAllAsync();
            }
            return countries;
        }
        [HttpGet(nameof(GetCurrencies))]
        [AllowAnonymous]
        public async Task<ActionResult<List<Currency>>> GetCurrencies()
        {
            var currencies = await OwnersUnitOfWork.Currencies.GetAllAsync();
            if(currencies.Count == 0)
            {
                await FillinCurrencies();
                currencies = await OwnersUnitOfWork.Currencies.GetAllAsync();
            }
            var countries = await OwnersUnitOfWork.Countries.GetAllAsync();
            if (currencies.Count > 0)
            {
                foreach (var c in countries)
                {
                    var Currency = currencies.Find(x => x.CurrencyCode == c.CurrencyCode);
                    if (Currency != null)
                        c.CurrencyId = Currency.Id;
                }
                await OwnersUnitOfWork.SaveAsync();
            }
            return currencies;
        }

        private async Task FillinCurrencies()
        {
            Currency[] Currenies = new Currency[]
            {
                new Currency(){CurrencyName ="Albanian lek", CurrencyCode = "ALL", CurrencySymbol= "L" },
                new Currency(){CurrencyName = "Afghan afghani", CurrencyCode = "AFN", CurrencySymbol= "؋"},
                new Currency(){CurrencyName = "Argentine peso" , CurrencyCode = "ARS", CurrencySymbol=	"$"},
                new Currency(){CurrencyName ="Aruban florin", CurrencyCode =   "AWG" , CurrencySymbol="ƒ"},
                new Currency(){CurrencyName ="Australia Dollar" , CurrencyCode =   "AUD", CurrencySymbol=	"$"},
                new Currency(){CurrencyName ="Armenian dram" , CurrencyCode =   "AMD", CurrencySymbol=  "֏"},
                new Currency(){CurrencyName ="Azerbaijani manat" , CurrencyCode =   "AZN", CurrencySymbol=	"₼"},
                new Currency(){CurrencyName ="The Antarctic dollar" , CurrencyCode =   "AAD", CurrencySymbol=   "$"},
                new Currency(){CurrencyName ="Bahamian dollar", CurrencyCode =  "BSD", CurrencySymbol=	"$"},
                new Currency(){CurrencyName ="Bahraini dinar", CurrencyCode =  "BHD", CurrencySymbol=	"د.ب"},
                new Currency(){CurrencyName ="Barbados Dollar", CurrencyCode = "BBD", CurrencySymbol=	"$"},
                new Currency(){CurrencyName ="Bangladeshi taka", CurrencyCode = "BDT", CurrencySymbol=  "৳"},
                new Currency(){CurrencyName ="Belarusian ruble", CurrencyCode =   "BYN" , CurrencySymbol="Br"},
                new Currency(){CurrencyName ="Belize Dollar" , CurrencyCode =  "BZD" , CurrencySymbol="$"},
                new Currency(){CurrencyName ="Bermuda Dollar" , CurrencyCode = "BMD", CurrencySymbol=	"$"},
                new Currency(){CurrencyName ="Bhutanese ngultrum" , CurrencyCode = "BTN", CurrencySymbol=   "Nu."},
                new Currency(){CurrencyName ="Bolivia Bolíviano"  , CurrencyCode = "BOB", CurrencySymbol=   "Bs."},
                new Currency(){CurrencyName ="Bolivian MVDOL"  , CurrencyCode = "BOV", CurrencySymbol=   "b$."},
                new Currency(){CurrencyName ="Bosnia-Herzegovina Convertible Marka" , CurrencyCode ="BAM" , CurrencySymbol="KM"},
                new Currency(){CurrencyName ="Botswana pula" , CurrencyCode =  "BWP", CurrencySymbol= "P"},
                new Currency(){CurrencyName ="Bulgarian lev" , CurrencyCode =   "BGN" , CurrencySymbol="лв"},
                new Currency(){CurrencyName ="Brazilian real", CurrencyCode = "BRL" , CurrencySymbol="R$"},
                new Currency(){CurrencyName ="Brunei dollar" , CurrencyCode =   "BND", CurrencySymbol=	"$"},
                new Currency(){CurrencyName ="Burundian franc" , CurrencyCode =   "BIF", CurrencySymbol=    "FBu"},
                new Currency(){CurrencyName ="Cambodian riel"  , CurrencyCode = "KHR", CurrencySymbol=	"៛"},
                new Currency(){CurrencyName ="West African CFA franc"  , CurrencyCode = "XOF", CurrencySymbol=  "CFA"},
                new Currency(){CurrencyName ="Central African CFA franc"  , CurrencyCode = "XAF", CurrencySymbol=  "FCFA"},
                new Currency(){CurrencyName ="Canadian dollar" , CurrencyCode =  "CAD"	, CurrencySymbol="$"},
                new Currency(){CurrencyName ="Cape Verdean escudo" , CurrencyCode =  "CVE"	, CurrencySymbol="$"},
                new Currency(){CurrencyName ="Cayman Islands dollar" , CurrencyCode =  "KYD", CurrencySymbol=	"$"},
                new Currency(){CurrencyName ="Chilean peso" , CurrencyCode = "CLP", CurrencySymbol=	"$"},
                new Currency(){CurrencyName ="Unidad de Fomento" , CurrencyCode = "CLF", CurrencySymbol=	"UF"},
                new Currency(){CurrencyName ="China Yuan Renminbi", CurrencyCode = "CNY", CurrencySymbol=	"¥"},
                new Currency(){CurrencyName ="Colombian peso" , CurrencyCode =  "COP", CurrencySymbol=	"$"},
                new Currency(){CurrencyName ="Comorian franc" , CurrencyCode =  "KMF", CurrencySymbol=	"CF"},
                new Currency(){CurrencyName ="Congolese franc" , CurrencyCode =  "CDF", CurrencySymbol=	"FC"},
                new Currency(){CurrencyName ="Costa Rican colón" , CurrencyCode =   "CRC", CurrencySymbol=	"₡"},
                new Currency(){CurrencyName ="Croatian kuna"  , CurrencyCode =  "HRK" , CurrencySymbol="kn"},
                new Currency(){CurrencyName ="Cuban peso", CurrencyCode =   "CUP", CurrencySymbol=	"₱"},
                new Currency(){CurrencyName ="Cypriot pound", CurrencyCode =   "CYP", CurrencySymbol=   "£"},
                new Currency(){CurrencyName ="Czech koruna" , CurrencyCode =  "CZK", CurrencySymbol= "Kč"},
                new Currency(){CurrencyName ="Danish krone", CurrencyCode =   "DKK", CurrencySymbol= "kr"},
                new Currency(){CurrencyName ="Djiboutian franc", CurrencyCode =   "DJF", CurrencySymbol= "Fdj"},
                new Currency(){CurrencyName ="Dominican Peso", CurrencyCode = "DOP", CurrencySymbol= "$"},
                new Currency(){CurrencyName ="Eastern Caribbean dollar", CurrencyCode =   "XCD", CurrencySymbol=	"$"},
                new Currency(){CurrencyName ="Egyptian Pound", CurrencyCode = "EGP"	, CurrencySymbol="£"},
                new Currency(){CurrencyName ="Salvadoran colón"  , CurrencyCode = "SVC"	, CurrencySymbol="$"},
                new Currency(){CurrencyName ="Euro" , CurrencyCode =  "EUR", CurrencySymbol=	"€"},
                new Currency(){CurrencyName ="Eritrean nakfa" , CurrencyCode =  "ERN", CurrencySymbol=  "Nfk"},
                new Currency(){CurrencyName ="Estonian kroon" , CurrencyCode =  "EEK", CurrencySymbol=  "kr"},
                new Currency(){CurrencyName ="Ethiopian birr" , CurrencyCode =  "ETB", CurrencySymbol=  "Br"},
                new Currency(){CurrencyName ="Falkland Islands pound" , CurrencyCode =  "FKP", CurrencySymbol=	"£"},
                new Currency(){CurrencyName ="Faroese króna" , CurrencyCode =  "FOK", CurrencySymbol=   "kr"},
                new Currency(){CurrencyName ="Fiji Dollar", CurrencyCode = "FJD", CurrencySymbol=	"$"},
                new Currency(){CurrencyName ="CFP franc", CurrencyCode = "XPF", CurrencySymbol= "₣"},
                new Currency(){CurrencyName ="Gambian dalasi", CurrencyCode = "GMD", CurrencySymbol= "D"},
                new Currency(){CurrencyName ="Georgian lari", CurrencyCode = "GEL", CurrencySymbol= "ლ"},
                new Currency(){CurrencyName ="Ghanaian cedi" , CurrencyCode = "GHS", CurrencySymbol=	"¢"},
                new Currency(){CurrencyName ="Gibraltar pound", CurrencyCode = "GIP"	, CurrencySymbol="£"},
                new Currency(){CurrencyName ="Guatemalan quetza", CurrencyCode =   "GTQ", CurrencySymbol= "Q"},
                new Currency(){CurrencyName ="Guernsey pound" , CurrencyCode = "GGP", CurrencySymbol=	"£"},
                new Currency(){CurrencyName ="Guinean franc" , CurrencyCode = "GNF", CurrencySymbol=    "GFr"},
                new Currency(){CurrencyName ="Guinea-Bissau peso" , CurrencyCode = "GWP", CurrencySymbol=    "₱"},
                new Currency(){CurrencyName ="Guyanese dollar" , CurrencyCode =  "GYD"	, CurrencySymbol="$"},
                new Currency(){CurrencyName ="Haitian gourde" , CurrencyCode =  "HTG"	, CurrencySymbol="G"},
                new Currency(){CurrencyName ="Honduran lempira"  , CurrencyCode = "HNL", CurrencySymbol= "L"},
                new Currency(){CurrencyName ="Hong Kong Dollar" , CurrencyCode =   "HKD", CurrencySymbol="$"},
                new Currency(){CurrencyName ="Hungarian forint" , CurrencyCode = "HUF" , CurrencySymbol="Ft"},
                new Currency(){CurrencyName ="Icelandic króna " , CurrencyCode = "ISK", CurrencySymbol= "kr"},
                new Currency(){CurrencyName ="Indian rupee", CurrencyCode = "INR", CurrencySymbol=	"₹"},
                new Currency(){CurrencyName ="Indonesian rupiah" , CurrencyCode =  "IDR", CurrencySymbol= "Rp"},
                new Currency(){CurrencyName ="Iranian rial" , CurrencyCode =  "IRR", CurrencySymbol=	"﷼"},
                new Currency(){CurrencyName ="Iraqi dinar" , CurrencyCode =  "IQD", CurrencySymbol= "ع.د"},
                new Currency(){CurrencyName ="Manx pound" , CurrencyCode =  "IMP", CurrencySymbol=	"£"},
                new Currency(){CurrencyName ="Israeli Shekel " , CurrencyCode = "ILS", CurrencySymbol=	"₪"},
                new Currency(){CurrencyName ="Jamaican dollar" , CurrencyCode = "JMD", CurrencySymbol= "J$"},
                new Currency(){CurrencyName ="Japanese yen" , CurrencyCode =  "JPY", CurrencySymbol=	"¥"},
                new Currency(){CurrencyName ="Jersey pound" , CurrencyCode =   "JEP"	, CurrencySymbol="£"},
                new Currency(){CurrencyName ="Jordanian dinar" , CurrencyCode =   "JOD" , CurrencySymbol="د.ا"},
                new Currency(){CurrencyName ="Kazakhstani tenge" , CurrencyCode =   "KZT", CurrencySymbol= "₸"},
                new Currency(){CurrencyName ="Kenyan shilling" , CurrencyCode =   "KES", CurrencySymbol= "Ksh"},
                new Currency(){CurrencyName ="Kiribati dollar" , CurrencyCode =   "KID", CurrencySymbol= "$"},
                new Currency(){CurrencyName ="North Korean won" , CurrencyCode =  "KPW", CurrencySymbol=	"₩"},
                new Currency(){CurrencyName ="Kuwaiti dinar" , CurrencyCode =  "KWD", CurrencySymbol=   "KD"},
                new Currency(){CurrencyName ="Kyrgyzstani som"  , CurrencyCode ="KGS" , CurrencySymbol="Лв"},
                new Currency(){CurrencyName ="Lao kip"  , CurrencyCode =  "LAK", CurrencySymbol=	"₭"},
                new Currency(){CurrencyName ="Latvian lats"  , CurrencyCode =  "LVL", CurrencySymbol=	"Ls"},
                new Currency(){CurrencyName ="Angolan kwanza"  , CurrencyCode =  "AOA", CurrencySymbol=  "Kz"},
                new Currency(){CurrencyName ="Lebanese pound" , CurrencyCode =  "LBP", CurrencySymbol=	"£"},
                new Currency(){CurrencyName ="Lesotho loti" , CurrencyCode =  "LSL", CurrencySymbol=	"L"},
                new Currency(){CurrencyName ="Liberian dollar"  , CurrencyCode ="LRD", CurrencySymbol=	"$"},
                new Currency(){CurrencyName ="Libyan dinar"  , CurrencyCode ="LYD", CurrencySymbol= "LD"},
                new Currency(){CurrencyName ="Lithuanian litas"  , CurrencyCode ="LTL", CurrencySymbol= "Lt"},
                new Currency(){CurrencyName ="Macanese pataca", CurrencyCode = "MOP" , CurrencySymbol="MOP$"},
                new Currency(){CurrencyName ="Macedonian Denar", CurrencyCode = "MKD" , CurrencySymbol="ден"},
                new Currency(){CurrencyName ="Malagasy ariary", CurrencyCode = "MGA" , CurrencySymbol="Ar"},
                new Currency(){CurrencyName ="Malagasy franc", CurrencyCode = "MGF" , CurrencySymbol="MF"},
                new Currency(){CurrencyName ="Malawian kwacha", CurrencyCode = "MWK" , CurrencySymbol="MK"},
                new Currency(){CurrencyName ="Malaysian ringgit"  , CurrencyCode =  "MYR" , CurrencySymbol="RM"},
                new Currency(){CurrencyName ="Maldivian rufiyaa"  , CurrencyCode =  "MVR" , CurrencySymbol="Rf"},
                new Currency(){CurrencyName ="Maltese lira"  , CurrencyCode =  "MTL" , CurrencySymbol="₤M"},
                new Currency(){CurrencyName ="Mauritanian ouguiya"  , CurrencyCode =  "MRU" , CurrencySymbol="UM"},
                new Currency(){CurrencyName ="Mauritius Rupee", CurrencyCode = "MUR", CurrencySymbol=	"₨"},
                new Currency(){CurrencyName ="Mexican Peso" , CurrencyCode ="MXN", CurrencySymbol=	"$"},
                new Currency(){CurrencyName ="Moldovan leu" , CurrencyCode ="MDL", CurrencySymbol=	"L"},
                new Currency(){CurrencyName ="Mongolian tögrög"  , CurrencyCode =  "MNT", CurrencySymbol=	"₮"},
                new Currency(){CurrencyName ="Moroccan dirham", CurrencyCode = "MAD" , CurrencySymbol= "MAD"},
                new Currency(){CurrencyName ="Mozambican metical" , CurrencyCode = "MZN", CurrencySymbol= "MT"},
                new Currency(){CurrencyName ="Myanmar kyat" , CurrencyCode = "MMK", CurrencySymbol= "K"},
                new Currency(){CurrencyName ="Namibian dollar" , CurrencyCode = "NAD", CurrencySymbol=	"$"},
                new Currency(){CurrencyName ="Nepalese rupee" , CurrencyCode ="NPR", CurrencySymbol=	"₨"},
                new Currency(){CurrencyName ="Netherlands Antillean guilder"  , CurrencyCode = "ANG", CurrencySymbol= "ƒ"},
                new Currency(){CurrencyName ="New Zealand Dollar" , CurrencyCode = "NZD"	, CurrencySymbol="$"},
                new Currency(){CurrencyName ="Nicaraguan córdoba" , CurrencyCode =  "NIO", CurrencySymbol= "C$"},
                new Currency(){CurrencyName ="Nigerian naira"  , CurrencyCode = "NGN", CurrencySymbol=	"₦"},
                new Currency(){CurrencyName ="Norwegian krone"  , CurrencyCode =  "NOK", CurrencySymbol= "kr"},
                new Currency(){CurrencyName ="Omani rial"  , CurrencyCode = "OMR"	, CurrencySymbol="﷼"},
                new Currency(){CurrencyName ="Pakistani rupee" , CurrencyCode = "PKR", CurrencySymbol=	"₨"},
                new Currency(){CurrencyName ="Panamanian balboa" , CurrencyCode =  "PAB", CurrencySymbol= "B/."},
                new Currency(){CurrencyName ="Papua New Guinean kina" , CurrencyCode =  "PGK", CurrencySymbol= "K"},
                new Currency(){CurrencyName ="Paraguayan guaraní" , CurrencyCode =  "PYG", CurrencySymbol= "₲"},
                new Currency(){CurrencyName ="Sol"  , CurrencyCode =  "PEN", CurrencySymbol= "S/."},
                new Currency(){CurrencyName ="Philippine peso"  , CurrencyCode =  "PHP", CurrencySymbol=	"₱"},
                new Currency(){CurrencyName ="Polish złoty "  , CurrencyCode = "PLN" , CurrencySymbol="zł"},
                new Currency(){CurrencyName ="Qatari Riyal", CurrencyCode = "QAR", CurrencySymbol=	"﷼"},
                new Currency(){CurrencyName ="Romanian leu", CurrencyCode = "RON" , CurrencySymbol= "lei"},
                new Currency(){CurrencyName ="Russian Ruble" , CurrencyCode =  "RUB", CurrencySymbol=	"₽"},
                new Currency(){CurrencyName ="Rwandan franc" , CurrencyCode =  "RWF", CurrencySymbol=   "R₣"},
                new Currency(){CurrencyName ="Saint Helena pound" , CurrencyCode = "SHP", CurrencySymbol=	"£"},
                new Currency(){CurrencyName ="Samoan tālā" , CurrencyCode = "WST", CurrencySymbol=  "WS$"},
                new Currency(){CurrencyName ="São Tomé and Príncipe dobra" , CurrencyCode = "STD", CurrencySymbol=  "Db"},
                new Currency(){CurrencyName ="Saudi riyal"  , CurrencyCode ="SAR", CurrencySymbol=	"﷼"},
                new Currency(){CurrencyName ="Serbian dinar"   , CurrencyCode = "RSD", CurrencySymbol= "Дин."},
                new Currency(){CurrencyName ="Algerian Dinar"   , CurrencyCode = "DZD", CurrencySymbol= "دج"},
                new Currency(){CurrencyName ="Seychelles Rupee"  , CurrencyCode =  "SCR", CurrencySymbol=	"₨"},
                new Currency(){CurrencyName ="Sierra Leonean leone"  , CurrencyCode =  "SLL", CurrencySymbol=	"Le"},
                new Currency(){CurrencyName ="Singapore Dollar" , CurrencyCode =  "SGD"	, CurrencySymbol="$"},
                new Currency(){CurrencyName ="Solomon Islands dollar" , CurrencyCode = "SBD", CurrencySymbol=	"$"},
                new Currency(){CurrencyName ="Somali shilling"  , CurrencyCode = "SOS" , CurrencySymbol="Sh"},
                new Currency(){CurrencyName ="South Korean won "  , CurrencyCode = "KRW", CurrencySymbol=	"₩"},
                new Currency(){CurrencyName ="South Africa Rand"   , CurrencyCode ="ZAR", CurrencySymbol= "R"},
                new Currency(){CurrencyName ="Falkland Islands pound"   , CurrencyCode ="FKP", CurrencySymbol= "£"},
                new Currency(){CurrencyName ="Sri Lankan rupee", CurrencyCode = "LKR"	, CurrencySymbol="₨"},
                new Currency(){CurrencyName ="Sudanese pound", CurrencyCode = "SDG" , CurrencySymbol="£"},
                new Currency(){CurrencyName ="Swazi lilangeni", CurrencyCode = "SZL" , CurrencySymbol="L"},
                new Currency(){CurrencyName ="Swedish krona"  , CurrencyCode =  "SEK" , CurrencySymbol="kr"},
                new Currency(){CurrencyName ="Swiss franc"  , CurrencyCode = "CHF" , CurrencySymbol="CHF"},
                new Currency(){CurrencyName ="Suriname Dollar" , CurrencyCode ="SRD", CurrencySymbol=	"$"},
                new Currency(){CurrencyName ="Syrian pound" , CurrencyCode ="SYP"	, CurrencySymbol="£"},
                new Currency(){CurrencyName ="New Taiwan dollar" , CurrencyCode =  "TWD" , CurrencySymbol="NT$"},
                new Currency(){CurrencyName ="Tajikistani somoni" , CurrencyCode =  "TJS" , CurrencySymbol="SM"},
                new Currency(){CurrencyName ="Tanzanian shilling" , CurrencyCode =  "TZS" , CurrencySymbol="TSh"},
                new Currency(){CurrencyName ="Thai baht" , CurrencyCode = "THB", CurrencySymbol=	"฿"},
                new Currency(){CurrencyName ="Tongan paʻanga" , CurrencyCode = "TOP", CurrencySymbol=   "T$"},
                new Currency(){CurrencyName ="Trinidad and Tobago dollar" , CurrencyCode = "TTD", CurrencySymbol= "TT$"},
                new Currency(){CurrencyName ="Tunisian dinar" , CurrencyCode = "TND", CurrencySymbol= "DT"},
                new Currency(){CurrencyName ="Turkish lira", CurrencyCode = "TRY"	, CurrencySymbol="₺"},
                new Currency(){CurrencyName ="Turkmenistani manat", CurrencyCode = "TMT"	, CurrencySymbol="T"},
                new Currency(){CurrencyName ="Tuvalu Dollar"  , CurrencyCode = "TVD"	, CurrencySymbol="$"},
                new Currency(){CurrencyName ="Ugandan shilling"  , CurrencyCode = "UGX" , CurrencySymbol="USh"},
                new Currency(){CurrencyName ="Ukrainian hryvnia" , CurrencyCode ="UAH"	, CurrencySymbol="₴"},
                new Currency(){CurrencyName ="United Arab Emirates dirham"  , CurrencyCode ="AED" , CurrencySymbol= "د.إ"},
                new Currency(){CurrencyName ="Pound sterling"  , CurrencyCode =  "GBP", CurrencySymbol=	"£"},
                new Currency(){CurrencyName ="United States Dollar "  , CurrencyCode = "USD", CurrencySymbol=	"$"},
                new Currency(){CurrencyName ="Peso Uruguayo" , CurrencyCode =   "UYU"	, CurrencySymbol="$U"},
                new Currency(){CurrencyName ="Uzbekistani soʻm" , CurrencyCode = "UZS" , CurrencySymbol="so'm"},
                new Currency(){CurrencyName ="Vanuatu vatu" , CurrencyCode =  "VUV" , CurrencySymbol="VT"},
                new Currency(){CurrencyName ="Venezuela Bolívar" , CurrencyCode =  "VEF" , CurrencySymbol="Bs"},
                new Currency(){CurrencyName ="Vietnamese dong" , CurrencyCode =  "VND", CurrencySymbol=	"₫"},
                new Currency(){CurrencyName ="Yemeni rial" , CurrencyCode = "YER"	, CurrencySymbol="﷼"},
                new Currency(){CurrencyName ="Zambian kwacha", CurrencyCode = "ZMW" , CurrencySymbol="ZK"},
                new Currency(){CurrencyName ="Zimbabwe Dollar", CurrencyCode = "ZWD" , CurrencySymbol="Z$"},
            };
            await OwnersUnitOfWork.Currencies.AddRangeAsync(Currenies);
            await OwnersUnitOfWork.SaveAsync();
        }

        public async Task FillInCountries()
        {
                Country[] countries = new Country[]
                {
                   new Country() { CountryName = "Afghanistan", CountryNameCode = "AF", PhoneCode="+93", CurrencyCode="AFN" },
                   new Country() { CountryName = "Åland Islands", CountryNameCode = "AX", PhoneCode = "+358", CurrencyCode="EUR" },
                   new Country() { CountryName = "Albania", CountryNameCode = "AL", PhoneCode = "+355", CurrencyCode="ALL" },
                   new Country() { CountryName = "Algeria", CountryNameCode = "DZ", PhoneCode = "+213" , CurrencyCode="DZD"},
                   new Country() { CountryName = "American Samoa", CountryNameCode = "AS", PhoneCode = "+1" , CurrencyCode="USD"},
                   new Country() { CountryName = "Andorra", CountryNameCode = "AD", PhoneCode = "+376" , CurrencyCode="EUR"},
                   new Country() { CountryName = "Angola", CountryNameCode = "AO", PhoneCode = "+244", CurrencyCode="AOA" },
                   new Country() { CountryName =   "Anguilla", CountryNameCode = "AI", PhoneCode = "+1", CurrencyCode="XCD" },
                   new Country() { CountryName =   "Antarctica", CountryNameCode = "AQ",  PhoneCode = "+672", CurrencyCode="AAD" },
                   new Country() { CountryName =   "Antigua and Barbuda", CountryNameCode = "AG",  PhoneCode = "+1", CurrencyCode="XCD" },
                   new Country() { CountryName =   "Argentina", CountryNameCode = "AR",  PhoneCode = "+54" , CurrencyCode="ARS"},
                   new Country() { CountryName =   "Armenia", CountryNameCode = "AM",  PhoneCode = "+374" , CurrencyCode="AMD"},
                   new Country() { CountryName =   "Aruba", CountryNameCode = "AW",  PhoneCode = "+297", CurrencyCode="AWG" },
                   new Country() { CountryName =   "Australia", CountryNameCode = "AU", PhoneCode = "+61", CurrencyCode="AUD" },
                   new Country() { CountryName =  "Austria", CountryNameCode = "AT",  PhoneCode = "+43" , CurrencyCode="EUR"},
                   new Country() { CountryName =   "Azerbaijan", CountryNameCode = "AZ", PhoneCode = "+994" , CurrencyCode="AZN"},
                   new Country() { CountryName =   "Bahamas", CountryNameCode = "BS",  PhoneCode = "+1" , CurrencyCode="BSD"},
                   new Country() { CountryName =   "Bahrain", CountryNameCode = "BH", PhoneCode = "+973" , CurrencyCode="BHD"},
                   new Country() { CountryName =   "Bangladesh", CountryNameCode = "BD", PhoneCode = "+880" , CurrencyCode="BDT"},
                   new Country() { CountryName =   "Barbados", CountryNameCode = "BB",  PhoneCode = "+1" , CurrencyCode="BBD"},
                   new Country() { CountryName =   "Belarus", CountryNameCode = "BY", PhoneCode = "+375" , CurrencyCode="BYN"},
                   new Country() { CountryName =   "Belgium", CountryNameCode = "BE",  PhoneCode = "+32" , CurrencyCode="EUR"},
                    new Country() { CountryName =  "Belize", CountryNameCode = "BZ", PhoneCode = "+501" , CurrencyCode="BZD"},
                    new Country() { CountryName =  "Benin", CountryNameCode = "BJ", PhoneCode = "+229", CurrencyCode="XOF" },
                    new Country() { CountryName =  "Bermuda", CountryNameCode = "BM", PhoneCode = "+1", CurrencyCode="BMD" },
                    new Country() { CountryName =  "Bhutan", CountryNameCode = "BT",  PhoneCode = "+975" , CurrencyCode="BTN"},
                    new Country() { CountryName =  "Bolivia", CountryNameCode = "BO",  PhoneCode = "+591" , CurrencyCode="BOB"},
                      new Country() { CountryName ="Bosnia and Herzegovina", CountryNameCode = "BA", PhoneCode = "+387" , CurrencyCode="BAM"},
                      new Country() { CountryName ="Botswana", CountryNameCode = "BW", PhoneCode = "+267" , CurrencyCode="BWP"},
                      new Country() { CountryName ="Bouvet Island", CountryNameCode = "BV",  PhoneCode = "+55", CurrencyCode="NOK" },
                      new Country() { CountryName ="Brazil", CountryNameCode = "BR", PhoneCode = "+55", CurrencyCode="BRL" },
                      new Country() { CountryName ="British Indian Ocean Territory", CountryNameCode = "IO", PhoneCode = "+246" , CurrencyCode="USD"},
                      new Country() { CountryName ="Brunei Darussalam", CountryNameCode = "BN",  PhoneCode = "+673" , CurrencyCode="BND"},
                      new Country() { CountryName ="Bulgaria", CountryNameCode = "BG", PhoneCode = "+359", CurrencyCode="BGN" },
                      new Country() { CountryName ="Burkina Faso", CountryNameCode = "BF",   PhoneCode = "+226", CurrencyCode="XOF" },
                      new Country() { CountryName ="Burundi", CountryNameCode = "BI",   PhoneCode = "+257" , CurrencyCode="BIF"},
                      new Country() { CountryName ="Cambodia", CountryNameCode = "KH",   PhoneCode = "+855" , CurrencyCode="KHR"},
                      new Country() { CountryName ="Cameroon", CountryNameCode = "CM",   PhoneCode = "+237" , CurrencyCode="XAF"},
                      new Country() { CountryName ="Canada", CountryNameCode = "CA",   PhoneCode = "+1" , CurrencyCode="CAD"},
                      new Country() { CountryName ="Cape Verde", CountryNameCode = "CV",   PhoneCode = "+238" , CurrencyCode="CVE"},
                      new Country() { CountryName ="Cayman Islands", CountryNameCode = "KY",   PhoneCode = "+1", CurrencyCode="KYD" },
                      new Country() { CountryName ="Central African Republic", CountryNameCode = "CF",   PhoneCode = "+236" , CurrencyCode="XAF"},
                      new Country() { CountryName ="Chad", CountryNameCode = "TD",   PhoneCode = "+235" , CurrencyCode="XAF"},
                      new Country() { CountryName ="Chile", CountryNameCode = "CL",   PhoneCode = "+56", CurrencyCode="CLP" },
                      new Country() { CountryName ="China", CountryNameCode = "CN",   PhoneCode = "+86", CurrencyCode="CNY" },
                      new Country() { CountryName ="Christmas Island", CountryNameCode = "CX",   PhoneCode = "+61", CurrencyCode="AUD" },
                      new Country() { CountryName ="Cocos (Keeling) Islands", CountryNameCode = "CC",   PhoneCode = "+61", CurrencyCode="AUD" },
                      new Country() { CountryName ="Colombia", CountryNameCode = "CO",   PhoneCode = "+57", CurrencyCode="COP" },
                      new Country() { CountryName ="Comoros", CountryNameCode = "KM",   PhoneCode = "+269", CurrencyCode="KMF" },
                      new Country() { CountryName ="Congo", CountryNameCode = "CG",   PhoneCode = "+242" , CurrencyCode="XAF"},
                      new Country() { CountryName ="Congo, The Democratic Republic of the", CountryNameCode = "CD",   PhoneCode = "+243" , CurrencyCode="CDF"},
                      new Country() { CountryName ="Cook Islands", CountryNameCode = "CK",   PhoneCode = "+682" , CurrencyCode="NZD"},
                      new Country() { CountryName ="Costa Rica", CountryNameCode = "CR",   PhoneCode = "+506" , CurrencyCode="CRC"},
                      new Country() { CountryName ="Côte d'Ivoire", CountryNameCode = "CI",   PhoneCode = "+225" , CurrencyCode="XOF"},
                      new Country() { CountryName ="Croatia", CountryNameCode = "HR",   PhoneCode = "+385" , CurrencyCode="HRK"},
                      new Country() { CountryName ="Cuba", CountryNameCode = "CU",   PhoneCode = "+53" , CurrencyCode="CUP"},
                      new Country() { CountryName ="Cyprus", CountryNameCode = "CY",   PhoneCode = "+357" , CurrencyCode="CYP"},
                      new Country() { CountryName ="Czech Republic", CountryNameCode = "CZ",   PhoneCode = "+420" , CurrencyCode="CZK"},
                      new Country() { CountryName ="Denmark", CountryNameCode = "DK",   PhoneCode = "+45" , CurrencyCode="DKK"},
                      new Country() { CountryName ="Djibouti", CountryNameCode = "DJ",   PhoneCode = "+253" , CurrencyCode="DJF"},
                      new Country() { CountryName ="Dominica", CountryNameCode = "DM",   PhoneCode = "+1" , CurrencyCode="XCD"},
                      new Country() { CountryName ="Dominican Republic", CountryNameCode = "DO",   PhoneCode = "+1" , CurrencyCode="DOP"},
                      new Country() { CountryName ="Ecuador", CountryNameCode = "EC",   PhoneCode = "+593" , CurrencyCode="USD"},
                      new Country() { CountryName ="Egypt", CountryNameCode = "EG",   PhoneCode = "+20" , CurrencyCode="EGP"},
                      new Country() { CountryName ="El Salvador", CountryNameCode = "SV",   PhoneCode = "+503" , CurrencyCode="SVC"},
                      new Country() { CountryName ="Equatorial Guinea", CountryNameCode = "GQ",   PhoneCode = "+240" , CurrencyCode="XAF"},
                      new Country() { CountryName ="Eritrea", CountryNameCode = "ER",   PhoneCode = "+291" , CurrencyCode="ERN"},
                      new Country() { CountryName ="Estonia", CountryNameCode = "EE",   PhoneCode = "+372" , CurrencyCode="EEK"},
                      new Country() { CountryName ="Ethiopia", CountryNameCode = "ET",   PhoneCode = "+251" , CurrencyCode="ETB"},
                      new Country() { CountryName ="Falkland Islands (Malvinas)", CountryNameCode = "FK",   PhoneCode = "+500", CurrencyCode="FKP" },
                      new Country() { CountryName ="Faroe Islands", CountryNameCode = "FO",   PhoneCode = "+298" , CurrencyCode="DKK"},
                      new Country() { CountryName ="Fiji", CountryNameCode = "FJ",   PhoneCode = "+679" , CurrencyCode="FJD"},
                      new Country() { CountryName ="Finland", CountryNameCode = "FI",   PhoneCode = "+358" , CurrencyCode="EUR"},
                      new Country() { CountryName ="France", CountryNameCode = "FR",   PhoneCode = "+33" , CurrencyCode="EUR"},
                      new Country() { CountryName ="French Guiana", CountryNameCode = "GF",   PhoneCode = "+594", CurrencyCode="EUR" },
                      new Country() { CountryName ="French Polynesia", CountryNameCode = "PF",   PhoneCode = "+689" , CurrencyCode="XPF"},
                      new Country() { CountryName ="French Southern Territories", CountryNameCode = "TF",   PhoneCode = "+262" , CurrencyCode="EUR"},
                      new Country() { CountryName ="Gabon", CountryNameCode = "GA",   PhoneCode = "+241" , CurrencyCode="XAF"},
                      new Country() { CountryName ="Gambia", CountryNameCode = "GM",   PhoneCode = "+220" , CurrencyCode="GMD"},
                      new Country() { CountryName ="Georgia", CountryNameCode = "GE",   PhoneCode = "+995" , CurrencyCode="GEL"},
                      new Country() { CountryName ="Germany", CountryNameCode = "DE",   PhoneCode = "+49" , CurrencyCode="EUR"},
                      new Country() { CountryName ="Ghana", CountryNameCode = "GH",   PhoneCode = "+233" , CurrencyCode="GHS"},
                      new Country() { CountryName ="Gibraltar", CountryNameCode = "GI",   PhoneCode = "+350", CurrencyCode="GIP" },
                      new Country() { CountryName ="Greece", CountryNameCode = "GR",   PhoneCode = "+30" , CurrencyCode="EUR"},
                      new Country() { CountryName ="Greenland", CountryNameCode = "GL",   PhoneCode = "+299" , CurrencyCode="DKK"},
                      new Country() { CountryName ="Grenada", CountryNameCode = "GD",   PhoneCode = "+1" , CurrencyCode="XCD"},
                      new Country() { CountryName ="Guadeloupe", CountryNameCode = "GP",   PhoneCode = "+590" , CurrencyCode="EUR"},
                      new Country() { CountryName ="Guam", CountryNameCode = "GU",   PhoneCode = "+1" , CurrencyCode="USD"},
                      new Country() { CountryName ="Guatemala", CountryNameCode = "GT",   PhoneCode = "+502" , CurrencyCode="GTQ"},
                      new Country() { CountryName ="Guernsey", CountryNameCode = "GG",   PhoneCode = "+44" , CurrencyCode="GGP"},
                      new Country() { CountryName ="Guinea", CountryNameCode = "GN",   PhoneCode = "+224" , CurrencyCode="GNF"},
                      new Country() { CountryName ="Guinea-Bissau", CountryNameCode = "GW",   PhoneCode = "+245" , CurrencyCode="GWP"},
                      new Country() { CountryName ="Guyana", CountryNameCode = "GY",   PhoneCode = "+592" , CurrencyCode="GYD"},
                      new Country() { CountryName ="Haiti", CountryNameCode = "HT",   PhoneCode = "+509" , CurrencyCode="HTG"},
                      new Country() { CountryName ="Heard Island and Mcdonald Islands", CountryNameCode = "HM",   PhoneCode = "+672" , CurrencyCode="AUD"},
                      new Country() { CountryName ="Holy See (Vatican City State)", CountryNameCode = "VA",   PhoneCode = "+379" , CurrencyCode="EUR"},
                      new Country() { CountryName ="Honduras", CountryNameCode = "HN",   PhoneCode = "+504" , CurrencyCode="HNL"},
                      new Country() { CountryName ="Hong Kong", CountryNameCode = "HK",   PhoneCode = "+852" , CurrencyCode="HKD"},
                      new Country() { CountryName ="Hungary", CountryNameCode = "HU",   PhoneCode = "+36" , CurrencyCode="HUF"},
                      new Country() { CountryName ="Iceland", CountryNameCode = "IS",   PhoneCode = "+354" , CurrencyCode="ISK"},
                      new Country() { CountryName ="India", CountryNameCode = "IN",   PhoneCode = "+91" , CurrencyCode="INR"},
                      new Country() { CountryName ="Indonesia", CountryNameCode = "ID",   PhoneCode = "+62" , CurrencyCode="IDR"},
                      new Country() { CountryName ="Iran, Islamic Republic Of", CountryNameCode = "IR",   PhoneCode = "+98", CurrencyCode="IRR" },
                      new Country() { CountryName ="Iraq", CountryNameCode = "IQ",   PhoneCode = "+964" , CurrencyCode="IQD"},
                      new Country() { CountryName ="Ireland", CountryNameCode = "IE",   PhoneCode = "+353" , CurrencyCode="EUR"},
                      new Country() { CountryName ="Isle of Man", CountryNameCode = "IM",   PhoneCode = "+44" , CurrencyCode="IMP"},
                      new Country() { CountryName ="Israel", CountryNameCode = "IL",   PhoneCode = "+972" , CurrencyCode="ILS"},
                      new Country() { CountryName ="Italy", CountryNameCode = "IT",   PhoneCode = "+39" , CurrencyCode="EUR"},
                      new Country() { CountryName ="Jamaica", CountryNameCode = "JM",   PhoneCode = "+1" , CurrencyCode="JMD"},
                      new Country() { CountryName ="Japan", CountryNameCode = "JP",   PhoneCode = "+81" , CurrencyCode="JPY"},
                      new Country() { CountryName ="Jersey", CountryNameCode = "JE",   PhoneCode = "+44" , CurrencyCode="JEP"},
                      new Country() { CountryName ="Jordan", CountryNameCode = "JO",   PhoneCode = "+962" , CurrencyCode="JOD"},
                      new Country() { CountryName ="Kazakhstan", CountryNameCode = "KZ",   PhoneCode = "+7" , CurrencyCode="KZT"},
                      new Country() { CountryName ="Kenya", CountryNameCode = "KE",   PhoneCode = "+254" , CurrencyCode="KES"},
                      new Country() { CountryName ="Kiribati", CountryNameCode = "KI",   PhoneCode = "+686" , CurrencyCode="KID"},
                      new Country() { CountryName ="Kuwait", CountryNameCode = "KW",   PhoneCode = "+965" , CurrencyCode="KWD"},
                      new Country() { CountryName ="Kyrgyzstan", CountryNameCode = "KG",   PhoneCode = "+996" , CurrencyCode="KGS"},
                      new Country() { CountryName ="Lao People'S Democratic Republic", CountryNameCode = "LA",   PhoneCode = "+856", CurrencyCode="LAK" },
                      new Country() { CountryName ="Latvia", CountryNameCode = "LV",   PhoneCode = "+371", CurrencyCode="LVL" },
                      new Country() { CountryName ="Lebanon", CountryNameCode = "LB",   PhoneCode = "+961" , CurrencyCode="LBP"},
                      new Country() { CountryName ="Lesotho", CountryNameCode = "LS",   PhoneCode = "+266" , CurrencyCode="LSL"},
                      new Country() { CountryName ="Liberia", CountryNameCode = "LR",   PhoneCode = "+231" , CurrencyCode="LRD"},
                      new Country() { CountryName ="Libyan Arab Jamahiriya", CountryNameCode = "LY",   PhoneCode = "+218", CurrencyCode="LYD" },
                      new Country() { CountryName ="Liechtenstein", CountryNameCode = "LI",   PhoneCode = "+423" , CurrencyCode="CHF"},
                      new Country() { CountryName ="Lithuania", CountryNameCode = "LT",   PhoneCode = "+370" , CurrencyCode="LTL"},
                      new Country() { CountryName ="Luxembourg", CountryNameCode ="LU",   PhoneCode = "+352" , CurrencyCode="EUR"},
                      new Country() { CountryName ="Macao", CountryNameCode = "MO",   PhoneCode = "+853" , CurrencyCode="MOP"},
                      new Country() { CountryName ="Macedonia, The Former Yugoslav Republic of", CountryNameCode = "MK",   PhoneCode = "+389" , CurrencyCode="MKD"},
                      new Country() { CountryName ="Madagascar", CountryNameCode = "MG",   PhoneCode = "+261" , CurrencyCode="MGA"},
                      new Country() { CountryName ="Malawi", CountryNameCode = "MW",   PhoneCode = "+265" , CurrencyCode="MWK"},
                      new Country() { CountryName ="Malaysia", CountryNameCode = "MY",   PhoneCode = "+60" , CurrencyCode="MYR"},
                      new Country() { CountryName ="Maldives", CountryNameCode = "MV",   PhoneCode = "+960" , CurrencyCode="MVR"},
                      new Country() { CountryName ="Mali", CountryNameCode = "ML",   PhoneCode = "+223" , CurrencyCode="XOF"},
                      new Country() { CountryName ="Malta", CountryNameCode = "MT",   PhoneCode = "+356", CurrencyCode="MTL" },
                      new Country() { CountryName ="Marshall Islands", CountryNameCode = "MH",   PhoneCode = "+692" , CurrencyCode="USD"},
                      new Country() { CountryName ="Martinique", CountryNameCode = "MQ",   PhoneCode = "+596" , CurrencyCode="EUR"},
                      new Country() { CountryName ="Mauritania", CountryNameCode = "MR",   PhoneCode = "+222" , CurrencyCode="MRU"},
                      new Country() { CountryName ="Mauritius", CountryNameCode = "MU",   PhoneCode = "+230" , CurrencyCode="MUR"},
                      new Country() { CountryName ="Mayotte", CountryNameCode = "YT",   PhoneCode = "+262" , CurrencyCode="EUR"},
                      new Country() { CountryName ="Mexico", CountryNameCode = "MX",   PhoneCode = "+52" , CurrencyCode="MXN"},
                      new Country() { CountryName ="Micronesia", CountryNameCode = "FM",   PhoneCode = "+691", CurrencyCode="USD" },
                      new Country() { CountryName ="Moldova", CountryNameCode = "MD",   PhoneCode = "+373" , CurrencyCode="MDL"},
                      new Country() { CountryName ="Monaco", CountryNameCode = "MC",   PhoneCode = "+377" , CurrencyCode="EUR"},
                      new Country() { CountryName ="Mongolia", CountryNameCode = "MN",   PhoneCode = "+976" , CurrencyCode="MNT"},
                      new Country() { CountryName ="Montserrat", CountryNameCode = "MS",   PhoneCode = "+1" , CurrencyCode="XCD"},
                      new Country() { CountryName ="Morocco", CountryNameCode = "MA",   PhoneCode = "+212", CurrencyCode="MAD" },
                      new Country() { CountryName ="Mozambique", CountryNameCode = "MZ",   PhoneCode = "+258" , CurrencyCode="MZN"},
                      new Country() { CountryName ="Myanmar", CountryNameCode = "MM",   PhoneCode = "+95" , CurrencyCode="MMK"},
                      new Country() { CountryName ="Namibia", CountryNameCode = "NA",   PhoneCode = "+264" , CurrencyCode="NAD"},
                      new Country() { CountryName ="Nauru", CountryNameCode = "NR",   PhoneCode = "+674" , CurrencyCode="AUD"},
                      new Country() { CountryName ="Nepal", CountryNameCode = "NP",   PhoneCode = "+977" , CurrencyCode="NPR"},
                      new Country() { CountryName ="Netherlands", CountryNameCode = "NL",   PhoneCode = "+31" , CurrencyCode="EUR"},
                      new Country() { CountryName ="Netherlands Antilles", CountryNameCode = "AN",   PhoneCode = "+599" , CurrencyCode="ANG"},
                      new Country() { CountryName ="New Caledonia", CountryNameCode = "NC",   PhoneCode = "+687" , CurrencyCode="XPF"},
                      new Country() { CountryName ="New Zealand", CountryNameCode = "NZ",   PhoneCode = "+64" , CurrencyCode="NZD"},
                      new Country() { CountryName ="Nicaragua", CountryNameCode = "NI",   PhoneCode = "+505" , CurrencyCode="NIO"},
                      new Country() { CountryName ="Niger", CountryNameCode = "NE",   PhoneCode = "+227" , CurrencyCode="XOF"},
                      new Country() { CountryName ="Nigeria", CountryNameCode = "NG",   PhoneCode = "+234" , CurrencyCode="NGN"},
                      new Country() { CountryName ="Niue", CountryNameCode = "NU",   PhoneCode = "+683" , CurrencyCode="NZD"},
                      new Country() { CountryName ="Norfolk Island", CountryNameCode = "NF",   PhoneCode = "+672" , CurrencyCode="AUD"},
                      new Country() { CountryName ="North Korea", CountryNameCode = "KP",   PhoneCode = "+850" , CurrencyCode="KPW"},
                      new Country() { CountryName ="Northern Mariana Islands", CountryNameCode = "MP",   PhoneCode = "+1", CurrencyCode="USD" },
                      new Country() { CountryName ="Norway", CountryNameCode = "NO",   PhoneCode = "+47" , CurrencyCode="NOK"},
                      new Country() { CountryName ="Oman", CountryNameCode = "OM",   PhoneCode = "+968" , CurrencyCode="OMR"},
                      new Country() { CountryName ="Pakistan", CountryNameCode = "PK",   PhoneCode = "+92" , CurrencyCode="PKR"},
                      new Country() { CountryName ="Palau", CountryNameCode = "PW",   PhoneCode = "+680" , CurrencyCode="USD"},
                      new Country() { CountryName ="Palestinian Territory, Occupied", CountryNameCode = "PS",   PhoneCode = "+970" , CurrencyCode="ILS"},
                      new Country() { CountryName ="Panama", CountryNameCode = "PA",   PhoneCode = "+507", CurrencyCode="PAB" },
                      new Country() { CountryName ="Papua New Guinea", CountryNameCode = "PG",   PhoneCode = "+675" , CurrencyCode="PGK"},
                      new Country() { CountryName ="Paraguay", CountryNameCode = "PY",   PhoneCode = "+595", CurrencyCode="PYG" },
                      new Country() { CountryName ="Peru", CountryNameCode = "PE",   PhoneCode = "+51" , CurrencyCode="PEN"},
                      new Country() { CountryName ="Philippines", CountryNameCode = "PH",   PhoneCode = "+63", CurrencyCode="PHP" },
                      new Country() { CountryName ="Pitcairn", CountryNameCode = "PN",   PhoneCode = "+64", CurrencyCode="NZD" },
                      new Country() { CountryName ="Poland", CountryNameCode = "PL",   PhoneCode = "+48", CurrencyCode="PLN" },
                      new Country() { CountryName ="Portugal", CountryNameCode = "PT",   PhoneCode = "+351" , CurrencyCode="EUR"},
                      new Country() { CountryName ="Puerto Rico", CountryNameCode = "PR",   PhoneCode = "+1", CurrencyCode="USD" },
                      new Country() { CountryName ="Qatar", CountryNameCode = "QA",   PhoneCode = "+974", CurrencyCode="QAR" },
                      new Country() { CountryName ="Reunion", CountryNameCode = "RE",   PhoneCode = "+262" , CurrencyCode="EURs"},
                      new Country() { CountryName ="Romania", CountryNameCode = "RO",   PhoneCode = "+40" , CurrencyCode="RON"},
                      new Country() { CountryName ="Russian Federation", CountryNameCode = "RU",   PhoneCode = "+7" , CurrencyCode="RUB"},
                      new Country() { CountryName ="Rwanda", CountryNameCode = "RW",   PhoneCode = "+250" , CurrencyCode="RWF"},
                      new Country() { CountryName ="Saint Helena", CountryNameCode = "SH",   PhoneCode = "+290", CurrencyCode="SHP" },
                      new Country() { CountryName ="Saint Kitts and Nevis", CountryNameCode = "KN",   PhoneCode = "+1" , CurrencyCode="XCD"},
                      new Country() { CountryName ="Saint Lucia", CountryNameCode = "LC",   PhoneCode = "+1", CurrencyCode="XCD" },
                      new Country() { CountryName ="Saint Pierre and Miquelon", CountryNameCode = "PM",   PhoneCode = "+508" , CurrencyCode="EUR"},
                      new Country() { CountryName ="Saint Vincent and the Grenadines", CountryNameCode = "VC",   PhoneCode = "+1" , CurrencyCode="XCD"},
                      new Country() { CountryName ="Samoa", CountryNameCode = "WS",   PhoneCode = "+685" , CurrencyCode="WST"},
                      new Country() { CountryName ="San Marino", CountryNameCode = "SM",   PhoneCode = "+378" , CurrencyCode="EUR"},
                      new Country() { CountryName ="Sao Tome and Principe", CountryNameCode = "ST",   PhoneCode = "+239" , CurrencyCode="STD"},
                      new Country() { CountryName ="Saudi Arabia", CountryNameCode = "SA",   PhoneCode = "+966" , CurrencyCode="SAR"},
                      new Country() { CountryName ="Senegal", CountryNameCode = "SN",   PhoneCode = "+221" , CurrencyCode="XOF"},
                      new Country() { CountryName ="Serbia and Montenegro", CountryNameCode = "CS",   PhoneCode = "+381" , CurrencyCode="RSD"},
                      new Country() { CountryName ="Seychelles", CountryNameCode = "SC",   PhoneCode = "+248" , CurrencyCode="SCR"},
                      new Country() { CountryName ="Sierra Leone", CountryNameCode = "SL",   PhoneCode = "+232" , CurrencyCode="SLL"},
                      new Country() { CountryName ="Singapore", CountryNameCode = "SG",   PhoneCode = "+65" , CurrencyCode="SGD"},
                      new Country() { CountryName ="Slovakia", CountryNameCode = "SK",   PhoneCode = "+421", CurrencyCode="EUR" },
                      new Country() { CountryName ="Slovenia", CountryNameCode = "SI",   PhoneCode = "+386" , CurrencyCode="EUR"},
                      new Country() { CountryName ="Solomon Islands", CountryNameCode = "SB",   PhoneCode = "+677" , CurrencyCode="SBD"},
                      new Country() { CountryName ="Somalia", CountryNameCode = "SO",   PhoneCode = "+252" , CurrencyCode="SOS"},
                      new Country() { CountryName ="South Africa", CountryNameCode = "ZA",   PhoneCode = "+27" , CurrencyCode="ZAR"},
                      new Country() { CountryName ="South Georgia and the South Sandwich Islands", CountryNameCode = "GS",   PhoneCode = "+500", CurrencyCode="GBP" },
                      new Country() { CountryName ="South Korea", CountryNameCode = "KR",   PhoneCode = "+82" , CurrencyCode="KRW"},
                      new Country() { CountryName ="Spain", CountryNameCode = "ES",   PhoneCode = "+34" , CurrencyCode="EUR"},
                      new Country() { CountryName ="Sri Lanka", CountryNameCode = "LK",   PhoneCode = "+94" , CurrencyCode="LKR"},
                      new Country() { CountryName ="Sudan", CountryNameCode = "SD",   PhoneCode = "+249" , CurrencyCode="SDG"},
                      new Country() { CountryName ="Suriname", CountryNameCode = "SR",   PhoneCode = "+597" , CurrencyCode="SRD"},
                      new Country() { CountryName ="Svalbard and Jan Mayen", CountryNameCode = "SJ",   PhoneCode = "+47" , CurrencyCode="NOK"},
                      new Country() { CountryName ="Swaziland", CountryNameCode = "SZ",   PhoneCode = "+268" , CurrencyCode="SZL"},
                      new Country() { CountryName ="Sweden", CountryNameCode = "SE",   PhoneCode = "+46" , CurrencyCode="SEK"},
                      new Country() { CountryName ="Switzerland", CountryNameCode = "CH",   PhoneCode = "+41" , CurrencyCode="CHF"},
                      new Country() { CountryName ="Syrian Arab Republic", CountryNameCode = "SY",   PhoneCode = "+963" , CurrencyCode="SYP"},
                      new Country() { CountryName ="Taiwan, Province of China", CountryNameCode = "TW",   PhoneCode = "+886" , CurrencyCode="TWD"},
                      new Country() { CountryName ="Tajikistan", CountryNameCode = "TJ",   PhoneCode = "+992" , CurrencyCode="TJS"},
                      new Country() { CountryName ="Tanzania, United Republic of", CountryNameCode = "TZ",   PhoneCode = "+255" , CurrencyCode="TZS"},
                      new Country() { CountryName ="Thailand", CountryNameCode = "TH",   PhoneCode = "+66" , CurrencyCode="THB"},
                      new Country() { CountryName ="Timor-Leste", CountryNameCode = "TL",   PhoneCode = "+670" , CurrencyCode="USD"},
                      new Country() { CountryName ="Togo", CountryNameCode = "TG",   PhoneCode = "+228" , CurrencyCode="XOF"},
                      new Country() { CountryName ="Tokelau", CountryNameCode = "TK",   PhoneCode = "+690" , CurrencyCode="NZD"},
                      new Country() { CountryName ="Tonga", CountryNameCode = "TO",   PhoneCode = "+676" , CurrencyCode="TOP"},
                      new Country() { CountryName ="Trinidad and Tobago", CountryNameCode = "TT",   PhoneCode = "+868" , CurrencyCode="TTD"},
                      new Country() { CountryName ="Tunisia", CountryNameCode = "TN",   PhoneCode = "+216" , CurrencyCode="TND"},
                      new Country() { CountryName ="Turkey", CountryNameCode = "TR",   PhoneCode = "+90" , CurrencyCode="TRY"},
                      new Country() { CountryName ="Turkmenistan", CountryNameCode = "TM",   PhoneCode = "+993" , CurrencyCode="TMT"},
                      new Country() { CountryName ="Turks and Caicos Islands", CountryNameCode = "TC",   PhoneCode = "+1" , CurrencyCode="USD"},
                      new Country() { CountryName ="Tuvalu", CountryNameCode = "TV",   PhoneCode = "+688" , CurrencyCode="AUD"},
                      new Country() { CountryName ="Uganda", CountryNameCode = "UG",   PhoneCode = "+256" , CurrencyCode="UGX"},
                      new Country() { CountryName ="Ukraine", CountryNameCode = "UA",   PhoneCode = "+380" , CurrencyCode="UAH"},
                      new Country() { CountryName ="United Arab Emirates", CountryNameCode = "AE",   PhoneCode = "+971" , CurrencyCode="AED"},
                      new Country() { CountryName ="United Kingdom", CountryNameCode = "GB",   PhoneCode = "+44" , CurrencyCode="GBP"},
                      new Country() { CountryName ="United States", CountryNameCode = "US",   PhoneCode = "+1" , CurrencyCode="USD"},
                      new Country() { CountryName ="United States Minor Outlying Islands", CountryNameCode = "UM",   PhoneCode = "+246" , CurrencyCode="USD"},
                      new Country() { CountryName ="Uruguay", CountryNameCode = "UY",   PhoneCode = "+598" , CurrencyCode="UYU"},
                      new Country() { CountryName ="Uzbekistan", CountryNameCode = "UZ",   PhoneCode = "+998" , CurrencyCode="UZS"},
                      new Country() { CountryName ="Vanuatu", CountryNameCode = "VU",   PhoneCode = "+678" , CurrencyCode="VUV"},
                      new Country() { CountryName ="Venezuela", CountryNameCode = "VE",   PhoneCode = "+58" , CurrencyCode="VEF"},
                      new Country() { CountryName ="Vietnam ", CountryNameCode = "VN",   PhoneCode = "+84" , CurrencyCode="VND"},
                      new Country() { CountryName ="Virgin Islands, British", CountryNameCode = "VG",   PhoneCode = "+1" , CurrencyCode="USD"},
                      new Country() { CountryName ="Virgin Islands, U.S.", CountryNameCode = "VI",   PhoneCode = "+1", CurrencyCode="USD" },
                      new Country() { CountryName ="Wallis and Futuna", CountryNameCode = "WF",   PhoneCode = "+681", CurrencyCode="XPF" },
                      new Country() { CountryName ="Western Sahara", CountryNameCode = "EH",   PhoneCode = "+212" , CurrencyCode="MAD"},
                      new Country() { CountryName ="Yemen", CountryNameCode = "YE",   PhoneCode = "+967" , CurrencyCode="YER"},
                      new Country() { CountryName ="Zambia", CountryNameCode = "ZM",   PhoneCode = "+260" , CurrencyCode="ZMW"},
                      new Country() { CountryName ="Zimbabwe", CountryNameCode = "ZW",   PhoneCode = "+263" , CurrencyCode="ZWD"}
                };
                await OwnersUnitOfWork.Countries.AddRangeAsync(countries);
                await OwnersUnitOfWork.SaveAsync();
            
        }
    }
}
